name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: temurin
        cache: maven
    - name: Run the Maven tests
      run: mvn clean compile test
    - name: Run checkstyle (Christy Tseng)
      run: mvn checkstyle:check
    - name: Upload Checkstyle Report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-report
        path: target/checkstyle.html
    - name: Run PMD checks
      run: mvn pmd:check
    - name: Upload PMD Report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pmd-report
        path: target/pmd.xml
